// Generated by tools/gen_config_ui.py, edit that script instead.
.pragma library

var tabs = [
    {
        "title": "General",
        "groups": [
            {
                "title": "Timing",
                "fields": [
                    {
                        "kind": "spin",
                        "key": "ShowDelay",
                        "label": "Delay before showing:",
                        "tooltip": "Wait before showing the indicator. Switches made during the delay only show the last one.",
                        "min": 0,
                        "max": 2000,
                        "suffix": " ms"
                    },
                    {
                        "kind": "spin",
                        "key": "FadeInDuration",
                        "label": "Fade in:",
                        "tooltip": "How long the indicator takes to appear.",
                        "min": 0,
                        "max": 2000,
                        "suffix": " ms"
                    },
                    {
                        "kind": "spin",
                        "key": "DisplayDuration",
                        "label": "Display time:",
                        "tooltip": "How long the indicator stays fully visible.",
                        "min": 100,
                        "max": 10000,
                        "suffix": " ms"
                    },
                    {
                        "kind": "spin",
                        "key": "FadeOutDuration",
                        "label": "Fade out:",
                        "tooltip": "How long the indicator takes to disappear.",
                        "min": 0,
                        "max": 2000,
                        "suffix": " ms"
                    },
                    {
                        "kind": "combo",
                        "key": "AppearEffect",
                        "label": "Appear effect:",
                        "tooltip": "",
                        "items": [
                            "Fade",
                            "Fade and zoom"
                        ]
                    }
                ]
            },
            {
                "title": "Highlight animation",
                "fields": [
                    {
                        "kind": "combo",
                        "key": "HighlightMotion",
                        "label": "Motion:",
                        "tooltip": "Follow: the highlight slides with the desktops and follows swipe gestures. Once done: the previous desktop fades out while the new one fades in.",
                        "items": [
                            "Follow the desktop switch",
                            "Once the switch is done"
                        ]
                    },
                    {
                        "kind": "spin",
                        "key": "AnimationDuration",
                        "label": "Duration:",
                        "tooltip": "Transition from the previous desktop to the new one.",
                        "min": 0,
                        "max": 2000,
                        "suffix": " ms"
                    },
                    {
                        "kind": "combo",
                        "key": "AnimationEasing",
                        "label": "Curve:",
                        "tooltip": "",
                        "items": [
                            "Linear",
                            "Smooth",
                            "Overshoot",
                            "Ease in and out"
                        ]
                    }
                ]
            },
            {
                "title": "Content",
                "fields": [
                    {
                        "kind": "check",
                        "key": "HideWithSingleDesktop",
                        "text": "Do not show with a single desktop",
                        "tooltip": ""
                    },
                    {
                        "kind": "combo",
                        "key": "Caption",
                        "label": "Desktop name:",
                        "tooltip": "Shows the name of the current desktop as a caption.",
                        "items": [
                            "Hidden",
                            "Above the indicator",
                            "Below the indicator"
                        ]
                    },
                    {
                        "kind": "combo",
                        "key": "Layout",
                        "label": "Layout:",
                        "tooltip": "Arrangement of the desktops inside the indicator.",
                        "items": [
                            "Follow the desktop grid",
                            "Single row",
                            "Single column"
                        ]
                    }
                ]
            }
        ]
    },
    {
        "title": "Position",
        "groups": [
            {
                "title": "Placement",
                "fields": [
                    {
                        "kind": "combo",
                        "key": "PositionMode",
                        "label": "Mode:",
                        "tooltip": "Anchor: one of nine screen points. Free position: percentages of the screen.",
                        "items": [
                            "Anchor",
                            "Free position"
                        ]
                    },
                    {
                        "kind": "check",
                        "key": "AvoidPanels",
                        "text": "Keep clear of panels",
                        "tooltip": "Places the indicator in the screen area not covered by panels."
                    }
                ]
            },
            {
                "title": "Anchor mode",
                "fields": [
                    {
                        "kind": "combo",
                        "key": "Anchor",
                        "label": "Anchor:",
                        "tooltip": "",
                        "items": [
                            "Top left",
                            "Top",
                            "Top right",
                            "Left",
                            "Center",
                            "Right",
                            "Bottom left",
                            "Bottom",
                            "Bottom right"
                        ]
                    },
                    {
                        "kind": "check",
                        "key": "SnapToAnchors",
                        "text": "Snap to anchors when dragging",
                        "tooltip": "With the settings app open, the indicator can be dragged. When dropped near an anchor, it sticks to it."
                    },
                    {
                        "kind": "spin",
                        "key": "SnapDistance",
                        "label": "Snap distance:",
                        "tooltip": "",
                        "min": 0,
                        "max": 500,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "Margin",
                        "label": "Margin:",
                        "tooltip": "Distance from the anchored screen edges.",
                        "min": 0,
                        "max": 2000,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "OffsetX",
                        "label": "Horizontal offset:",
                        "tooltip": "Positive values move right.",
                        "min": -5000,
                        "max": 5000,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "OffsetY",
                        "label": "Vertical offset:",
                        "tooltip": "Positive values move down.",
                        "min": -5000,
                        "max": 5000,
                        "suffix": " px"
                    }
                ]
            },
            {
                "title": "Free position mode",
                "fields": [
                    {
                        "kind": "dspin",
                        "key": "PercentX",
                        "label": "Horizontal position:",
                        "tooltip": "Position of the indicator center, from the left edge.",
                        "min": 0,
                        "max": 100,
                        "suffix": " %"
                    },
                    {
                        "kind": "dspin",
                        "key": "PercentY",
                        "label": "Vertical position:",
                        "tooltip": "Position of the indicator center, from the top edge.",
                        "min": 0,
                        "max": 100,
                        "suffix": " %"
                    }
                ]
            }
        ]
    },
    {
        "title": "Style",
        "groups": [
            {
                "title": "Style",
                "fields": [
                    {
                        "kind": "combo",
                        "key": "Style",
                        "label": "Style:",
                        "tooltip": "",
                        "items": [
                            "Pills",
                            "Labels",
                            "Icons",
                            "Open windows"
                        ]
                    },
                    {
                        "kind": "combo",
                        "key": "Highlight",
                        "label": "Highlight:",
                        "tooltip": "Highlight of the current desktop for the labels, icons and open windows styles.",
                        "items": [
                            "Full",
                            "Square",
                            "Line",
                            "Full with line"
                        ]
                    },
                    {
                        "kind": "check",
                        "key": "MarkOccupied",
                        "text": "Mark desktops that contain windows",
                        "tooltip": ""
                    },
                    {
                        "kind": "spin",
                        "key": "InactiveOpacity",
                        "label": "Inactive opacity:",
                        "tooltip": "Opacity of the other desktops.",
                        "min": 0,
                        "max": 100,
                        "suffix": " %"
                    },
                    {
                        "kind": "spin",
                        "key": "Spacing",
                        "label": "Spacing:",
                        "tooltip": "",
                        "min": 0,
                        "max": 200,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "Padding",
                        "label": "Padding:",
                        "tooltip": "Space between the desktops and the background edge.",
                        "min": 0,
                        "max": 200,
                        "suffix": " px"
                    }
                ]
            },
            {
                "title": "Pills",
                "fields": [
                    {
                        "kind": "combo",
                        "key": "PillShape",
                        "label": "Shape:",
                        "tooltip": "Circle and diamond use the heights as size.",
                        "items": [
                            "Pill",
                            "Circle",
                            "Square",
                            "Diamond",
                            "Bar"
                        ]
                    },
                    {
                        "kind": "spin",
                        "key": "PillWidth",
                        "label": "Width:",
                        "tooltip": "",
                        "min": 1,
                        "max": 500,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "PillHeight",
                        "label": "Height:",
                        "tooltip": "",
                        "min": 1,
                        "max": 500,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "PillActiveWidth",
                        "label": "Current desktop width:",
                        "tooltip": "",
                        "min": 1,
                        "max": 500,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "PillActiveHeight",
                        "label": "Current desktop height:",
                        "tooltip": "",
                        "min": 1,
                        "max": 500,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "PillRadius",
                        "label": "Corner radius:",
                        "tooltip": "",
                        "min": 0,
                        "max": 250,
                        "suffix": " px"
                    }
                ]
            },
            {
                "title": "Cells (labels, icons, open windows)",
                "fields": [
                    {
                        "kind": "combo",
                        "key": "CellShape",
                        "label": "Shape:",
                        "tooltip": "Shape of the cells and of the full and square highlights.",
                        "items": [
                            "Rounded",
                            "Circle",
                            "Square"
                        ]
                    },
                    {
                        "kind": "spin",
                        "key": "CellWidth",
                        "label": "Minimum width:",
                        "tooltip": "",
                        "min": 1,
                        "max": 500,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "CellHeight",
                        "label": "Height:",
                        "tooltip": "",
                        "min": 1,
                        "max": 500,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "CellRadius",
                        "label": "Corner radius:",
                        "tooltip": "",
                        "min": 0,
                        "max": 250,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "SquareSize",
                        "label": "Square highlight size:",
                        "tooltip": "",
                        "min": 1,
                        "max": 500,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "LineWidth",
                        "label": "Line highlight width:",
                        "tooltip": "",
                        "min": 1,
                        "max": 500,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "LineHeight",
                        "label": "Line highlight thickness:",
                        "tooltip": "",
                        "min": 1,
                        "max": 100,
                        "suffix": " px"
                    }
                ]
            }
        ]
    },
    {
        "title": "Labels and icons",
        "groups": [
            {
                "title": "Labels",
                "fields": [
                    {
                        "kind": "combo",
                        "key": "LabelSource",
                        "label": "Text:",
                        "tooltip": "",
                        "items": [
                            "Desktop number",
                            "Desktop name",
                            "Template",
                            "Custom list"
                        ]
                    },
                    {
                        "kind": "line",
                        "key": "LabelTemplate",
                        "label": "Template:",
                        "tooltip": "%d is replaced by the desktop number, %n by its name.",
                        "placeholder": "D%d"
                    },
                    {
                        "kind": "line",
                        "key": "LabelList",
                        "label": "Custom list:",
                        "tooltip": "One label per desktop, separated by commas. Missing entries show the number.",
                        "placeholder": "Web, Code, Mail"
                    },
                    {
                        "kind": "spin",
                        "key": "FontSize",
                        "label": "Font size:",
                        "tooltip": "0 uses the theme font size.",
                        "min": 0,
                        "max": 200,
                        "suffix": " px"
                    },
                    {
                        "kind": "check",
                        "key": "Bold",
                        "text": "Bold text",
                        "tooltip": ""
                    },
                    {
                        "kind": "check",
                        "key": "ActiveBold",
                        "text": "Bold text for the current desktop",
                        "tooltip": ""
                    }
                ]
            },
            {
                "title": "Icons",
                "fields": [
                    {
                        "kind": "line",
                        "key": "IconList",
                        "label": "Icons:",
                        "tooltip": "One icon name per desktop, separated by commas.",
                        "placeholder": "internet-web-browser, utilities-terminal"
                    },
                    {
                        "kind": "line",
                        "key": "IconFallback",
                        "label": "Fallback icon:",
                        "tooltip": "Used for desktops beyond the list.",
                        "placeholder": "virtual-desktops"
                    },
                    {
                        "kind": "spin",
                        "key": "IconSize",
                        "label": "Icon size:",
                        "tooltip": "",
                        "min": 8,
                        "max": 256,
                        "suffix": " px"
                    }
                ]
            },
            {
                "title": "Open windows",
                "fields": [
                    {
                        "kind": "spin",
                        "key": "TaskIconSize",
                        "label": "Window icon size:",
                        "tooltip": "",
                        "min": 8,
                        "max": 256,
                        "suffix": " px"
                    },
                    {
                        "kind": "spin",
                        "key": "MaxTaskIcons",
                        "label": "Icons per desktop:",
                        "tooltip": "Extra windows are shown as +n.",
                        "min": 1,
                        "max": 20,
                        "suffix": ""
                    }
                ]
            }
        ]
    },
    {
        "title": "Colors",
        "groups": [
            {
                "title": "Colors",
                "fields": [
                    {
                        "kind": "check",
                        "key": "UseThemeColors",
                        "text": "Use the Plasma theme colors",
                        "tooltip": "Uncheck to use the colors below."
                    },
                    {
                        "kind": "color",
                        "key": "ActiveColor",
                        "label": "Current desktop:",
                        "tooltip": ""
                    },
                    {
                        "kind": "color",
                        "key": "InactiveColor",
                        "label": "Other desktops (pills):",
                        "tooltip": ""
                    },
                    {
                        "kind": "color",
                        "key": "TextColor",
                        "label": "Text:",
                        "tooltip": ""
                    },
                    {
                        "kind": "color",
                        "key": "ActiveTextColor",
                        "label": "Text on the highlight:",
                        "tooltip": ""
                    },
                    {
                        "kind": "color",
                        "key": "OccupiedColor",
                        "label": "Desktop with windows mark:",
                        "tooltip": ""
                    }
                ]
            },
            {
                "title": "Background",
                "fields": [
                    {
                        "kind": "combo",
                        "key": "BackgroundMode",
                        "label": "Background:",
                        "tooltip": "",
                        "items": [
                            "Plasma theme",
                            "Plasma theme, solid",
                            "None",
                            "Custom color"
                        ]
                    },
                    {
                        "kind": "color",
                        "key": "BackgroundColor",
                        "label": "Custom color:",
                        "tooltip": ""
                    },
                    {
                        "kind": "spin",
                        "key": "BackgroundOpacity",
                        "label": "Opacity:",
                        "tooltip": "Opacity of the background only, the desktops stay opaque.",
                        "min": 0,
                        "max": 100,
                        "suffix": " %"
                    },
                    {
                        "kind": "spin",
                        "key": "BackgroundRadius",
                        "label": "Custom corner radius:",
                        "tooltip": "",
                        "min": 0,
                        "max": 250,
                        "suffix": " px"
                    }
                ]
            }
        ]
    }
];

// When a setting has an effect; the others are greyed out.
var enabledWhen = {
    Anchor: v => v.PositionMode === 0,
    SnapToAnchors: v => v.PositionMode === 0,
    SnapDistance: v => v.SnapToAnchors && v.PositionMode === 0,
    Margin: v => v.PositionMode === 0,
    OffsetX: v => v.PositionMode === 0,
    OffsetY: v => v.PositionMode === 0,
    PercentX: v => v.PositionMode === 1,
    PercentY: v => v.PositionMode === 1,
    Highlight: v => v.Style !== 0,
    MarkOccupied: v => v.Style !== 3,
    PillShape: v => v.Style === 0,
    PillWidth: v => v.Style === 0 && v.PillShape !== 1 && v.PillShape !== 3,
    PillHeight: v => v.Style === 0,
    PillActiveWidth: v => v.Style === 0 && v.PillShape !== 1 && v.PillShape !== 3,
    PillActiveHeight: v => v.Style === 0,
    PillRadius: v => v.Style === 0 && v.PillShape === 0,
    CellShape: v => v.Style !== 0,
    CellWidth: v => v.Style !== 0,
    CellHeight: v => v.Style !== 0,
    CellRadius: v => v.Style !== 0 && v.CellShape === 0,
    SquareSize: v => v.Style !== 0 && v.Highlight === 1,
    LineWidth: v => v.Style !== 0 && (v.Highlight === 2 || v.Highlight === 3),
    LineHeight: v => v.Style !== 0 && (v.Highlight === 2 || v.Highlight === 3),
    LabelSource: v => v.Style === 1,
    LabelTemplate: v => v.Style === 1 && v.LabelSource === 2,
    LabelList: v => v.Style === 1 && v.LabelSource === 3,
    FontSize: v => v.Style === 1 || v.Style === 3 || v.Caption !== 0,
    Bold: v => v.Style === 1 || v.Style === 3,
    ActiveBold: v => v.Style === 1 || v.Style === 3,
    IconList: v => v.Style === 2,
    IconFallback: v => v.Style === 2,
    IconSize: v => v.Style === 2,
    TaskIconSize: v => v.Style === 3,
    MaxTaskIcons: v => v.Style === 3,
    ActiveColor: v => !v.UseThemeColors,
    InactiveColor: v => !v.UseThemeColors && v.Style === 0,
    TextColor: v => !v.UseThemeColors && (v.Style !== 0 || v.Caption !== 0),
    ActiveTextColor: v => !v.UseThemeColors && v.Style !== 0 && (v.Highlight === 0 || v.Highlight === 1),
    OccupiedColor: v => !v.UseThemeColors && v.MarkOccupied && v.Style !== 3,
    BackgroundOpacity: v => v.BackgroundMode !== 2,
    BackgroundColor: v => v.BackgroundMode === 3,
    BackgroundRadius: v => v.BackgroundMode === 3
};
